### ISSUE TITLE
[Questions] There are plans to add support for `async-std`.?

### ISSUE THREAD

**Issue by 04l3x** [ngrok/ngrok-rust#118]
Hi, I wanted to use the rust ngrok sdk but when I went to the documentation and then to the source code I noticed that it is linked to the Tokio ecosystem, I guess it makes sense because it is the largest within the rust ecosystem.

But my stack is completely based on async-std and that's why my question, I would love to be able to use this package without having to change my stack.

**Comment by jrobsonchase** [comment]
Thanks for the issue!

We don't have any plans to add support for alternative runtimes right now, though personally I'd love to. A good chunk of the `muxado` crate was written to be entirely runtime-agnostic (see: [the `StreamManager` struct](https://github.com/ngrok/ngrok-rust/blob/main/muxado/src/stream_manager.rs), which manages all of the subtasks via a `FuturesUnordered`), but got fatigued around some of the higher-level bits, like [the `Heartbeat` wrapper](https://github.com/ngrok/ngrok-rust/blob/main/muxado/src/heartbeat.rs) :sweat_smile: 

Some follow-up questions for you:
* Is the tokio dependency a hard blocker for you, or is it something that can be worked around? If it can be worked around, how much effort does it take? Ideally, in lieu of full support for other runtimes, the fact that we're using tokio under the hood should be an implementation detail that shouldn't "infect" the rest of your codebase. If you're having to do weird things like carry around tokio `Handle`s to enter its runtime context to prevent panics or something, we'd like to know about it and fix it.
* In the ideal scenario, what does `async-std` support look like? Is it a set of features [like in `sqlx`](https://docs.rs/sqlx/latest/sqlx/#runtime-support) where you pick one at compile-time? Or is there a reasonable approach to being generic over executor implementations? I generally prefer the latter, but it doesn't seem like anyone has agreed on an executor/spawner trait to be generic over, and managing tasks internally quickly gets unwieldy :confused: 
* I just noticed the [`tokio1` feature in `async-std`](https://docs.rs/async-std/latest/async_std/#features). What does it do exactly?
