### ISSUE TITLE
Support the `app_protocol` option for HTTP and Labeled listeners

### ISSUE THREAD

**Issue by jrobsonchase** [ngrok/ngrok-rust#125]
This is to support http/2, and potentially other change-of-protocols that may occur.

See ngrok-private/ngrok#23863

Since we're Rusty here, let's maybe make it an enum rather than a string as it is in Go?

- [X] setup the app protocol to forward http2/http1/"" #130 
- [x] tls config alpn forwarding work

**Comment by CK-Ward** [comment]
HI @OfTheDelmer, do you have a WIP branch for this work?

**Comment by CK-Ward** [comment]
`string` is the decision
