### ISSUE TITLE
Update to hyper v1

### ISSUE THREAD

**Issue by jrobsonchase** [ngrok/ngrok-rust#126]
It's finally stable! :tada: 

I imagine everyone will be eager to move to the new version, so we should bump our dependency that we track for `Server` integration.

Should hopefully be a pretty easy transition since we aren't using a very large API surface area.

**Comment by Narsil** [comment]
Bumping, since it'd be nice for https://github.com/huggingface/text-generation-inference (Otherwise we might drop the ngrok tunelling which we were supporting the get edge load balancing done.

**Comment by bobzilladev** [comment]
Hello, thanks for the feedback! There is now this issue open which is related to hyper v1 support: https://github.com/ngrok/ngrok-rust/issues/136
