### ISSUE TITLE
Any chance of breaking muxado out into a separate repo?

### ISSUE THREAD

**Issue by anderspitman** [ngrok/ngrok-rust#134]
Seems useful on its own. A la muxado-go.

**Comment by salilsub** [comment]
We're investigating the feasibility and level of effort on this. Stay tuned!

**Comment by salilsub** [comment]
Muxado isn't something we intend to directly support outside of our own SDKs, so we won't be breaking it out of that repo. It is a separate crate so you can use it by itself if you want. However, we would not provide any support for that outside of our SDKs.

**Comment by anderspitman** [comment]
Fair enough; thanks for the followup @salilsub

**Comment by jrobsonchase** [comment]
It should also be noted that while it's not a separate repo, it's still a separate crate that you're free to consume on its own: https://crates.io/crates/muxado
