### ISSUE TITLE
Update needed due to breaking changes of axum  version "0.7.4" release 

### ISSUE THREAD

**Issue by 0xSchellen** [ngrok/ngrok-rust#136]
Can you please update to allow the use of the new axum "0.7.4" release. 
There were breaking changes of the axum Server sintax. 

error[E0433]: failed to resolve: could not find `Server` in `axum`
  --> src/main.rs:21:11
   |
21 |     axum::Server::builder(listener)
   |           ^^^^^^ could not find `Server` in `axum`

Thank you

**Comment by Abdiramen** [comment]
Thanks for bringing this to our attention! I'll take a look into this.

**Comment by SandmeyerX** [comment]
How is it going?
