### ISSUE TITLE
Read authtoken from ngrok.yml

### ISSUE THREAD

**Issue by manglemix** [ngrok/ngrok-rust#153]
This is mainly a convenience method but there should be an option read the authtoken directly from the config file.

**Comment by jrobsonchase** [comment]
Thanks for the suggestion!

I believe this is slated to be addressed in an upcoming API revision, but (to me at least) it feels like a slippery slope to trying to ingest the ngrok agent's configuration in its entirety, and figuring out how to give the caller access to all of the automatically-started endpoints seems tricky.

We get this request often enough that it's bound to happen eventually, if only for the initial connection options to begin with. Once that's available, we can see if people actually want the rest of the configuration and explore our API options then.

Anyway, can't give a specific timeline, but stay tuned!
